#include https://pages.frohnmeyer-wds.de/scripts/clone.yml

steps:
  - name: build_test
    image: gradle:9.4-jdk25-noble
    pull: true
    commands:
      - gradle --build-cache :dbusmenu4j:publish -Pmaven="https://maven.frohnmeyer-wds.de/artifacts"
    environment:
      MAVEN_TOKEN:
        from_secret: maven_token
      MAVEN_NAME:
        from_secret: maven_name